- name: Serverless
  # You may pin to the exact commit or the version.
  # uses: serverless/github-action@8f96a6db886d4ce30c6063dd9919a8a1a4a6d9cf
  uses: serverless/github-action@v1.53.0

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Serverless Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 14.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v1.53.0
      with:
        args: deploy
      env:
#         SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
#         or if using AWS credentials directly
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
