name: post-tweets-30-mins
on:
  # schedule:
  # - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  store-highlights:
    runs-on: ubuntu-latest
    steps:
      - name: Call the store highlights route
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: https://buds-bot.vercel.app/api/postTweet
          configuration: '{ "method": "GET", "headers": {"Authorization": "Bearer ${{ secrets.API_SECRET_KEY }}"} }'
